### PR TITLE
fix: nullable signature members

### PR DESCRIPTION
**Pull request by oSumAtrIX**
RE: #9 

This commit will allow "partial" signatures. Example usage:

```kt
val showVideoAdsMethodData = cache.methods["show-video-ads"].findParentMethod(
    Signature(
        "show-video-ads-method",
        null,
        null,
        arrayOf(Type.BOOLEAN_TYPE),
        null
    )
) ?: return PatchResultError("Could not find parent method to 'show-video-ads'")
```

This example will try to use the cached method `show-video-ads` to find the actual method `show-video-ads-method`. To find this method in our example, it is only required to match for the parameters, since in our example, no other method in the same class has this parameter.

### CODE REVIEW

**Review by Lucaskyy — APPROVED** [review]

**Comment by Lucaskyy** [comment]
@oSumAtrIX Could you review, please?

**Comment by oSumAtrIX** [comment]
Wouldn't L81 return to the inner lambda instead of the `cmp` method?

https://github.com/ReVancedTeam/revanced-patcher/blob/11e0f2ab6e844e2f28821418e6a820aa11738ed4/src/main/kotlin/net/revanced/patcher/resolver/MethodResolver.kt#L70-L81

**Comment by Lucaskyy** [comment]
Good catch! And no, it doesn't. But I'll make it explicitly return to the `cmp` method to be sure.

**Comment by Lucaskyy** [comment]
@oSumAtrIX All good now?

**Pull request merged**
